// <auto-generated />
using System;
using MachineLearningBTL.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MachineLearningBTL.Migrations
{
    [DbContext(typeof(MachineLearningDb))]
    [Migration("20231118025450_addWeather")]
    partial class addWeather
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MachineLearningBTL.Models.DiaBetes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<float>("BMI")
                        .HasColumnType("real");

                    b.Property<int>("BloodPressure")
                        .HasColumnType("int");

                    b.Property<float>("DiabetesPedigreeFunction")
                        .HasColumnType("real");

                    b.Property<int>("Glucose")
                        .HasColumnType("int");

                    b.Property<int>("Insulin")
                        .HasColumnType("int");

                    b.Property<int>("Outcome")
                        .HasColumnType("int");

                    b.Property<int>("Pregnancies")
                        .HasColumnType("int");

                    b.Property<int>("SkinThickness")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DiaBetes");
                });

            modelBuilder.Entity("MachineLearningBTL.Models.UserData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<float>("BMI")
                        .HasColumnType("real");

                    b.Property<int>("BloodPressure")
                        .HasColumnType("int");

                    b.Property<float>("DiabetesPedigreeFunction")
                        .HasColumnType("real");

                    b.Property<int>("Glucose")
                        .HasColumnType("int");

                    b.Property<int>("Insulin")
                        .HasColumnType("int");

                    b.Property<int>("Outcome")
                        .HasColumnType("int");

                    b.Property<int>("Pregnancies")
                        .HasColumnType("int");

                    b.Property<int>("SkinThickness")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("userDatas");
                });

            modelBuilder.Entity("MachineLearningBTL.Models.Weather", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("AnhSang")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<float>("DoAm")
                        .HasColumnType("real");

                    b.Property<float>("DoOn")
                        .HasColumnType("real");

                    b.Property<float>("KhiGas")
                        .HasColumnType("real");

                    b.Property<float>("NhietDo")
                        .HasColumnType("real");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("weathers");
                });
#pragma warning restore 612, 618
        }
    }
}
